### ISSUE TITLE
Disable ap2eth

### ISSUE THREAD

**Issue by MiguelBailonS** [espressif/esp-gateway#1]
Hi, my name is Miguel Bailon
I am working with the project esp-gateway and want to remove everything related for ethernet in order to reduce memory consumption and I RAM. 
Could you help me with that?

**Comment by tswen** [comment]
Hi Miguel,
Have you tried to remove the FEAT_TYPE_ETH part?

**Comment by MiguelBailonS** [comment]
Hi @tswen,
Yes, i did it, thanks you
Now, I see the IRAM used is 80%. Is there any way may I increase available IRAM?

**Comment by tswen** [comment]
Hi Miguel,

You can refer to the following link:
https://github.com/espressif/esp-idf/issues/2566
https://blog.espressif.com/esp32-memory-analysis-case-study-eacc75fe5431
I believe it will help you.

Also, if possible, you can also use PSRAM
https://docs.espressif.com/projects/esp-idf/en/release-v4.3/esp32/api-guides/external-ram.html

**Comment by MiguelBailonS** [comment]
Thank you! @tswen
